### PR TITLE
Allow the `images` input to be empty, which outputs just the raw tags

### PR DESCRIPTION
**Pull request by jasondamour**
Addresses #212

### CODE REVIEW

**Comment by jasondamour** [comment]
@crazy-max Can I get eyes on this before I resolve conflicts?

**Comment by jasondamour** [comment]
Intended usage is for build tools which only take the tags as input, not the full image url. For example, this is working today:

```
    - name: Docker Metadata
      id: docker-metadata
      uses: jasondamour/metadata-action@4a2a7878d3f53d548dc904024c8873d1fdb152be
      with:
        sep-tags: ','
        sep-labels: ','
        tags: ${{ env.DOCKER_TAGS_CONFIG }}
    - name: Maven Build
      run: >
        mvn jib:build
        -Djib.to.tags=${{ steps.platfom-svc-docker-metadata.outputs.tags }}
        -Djib.container.labels=${{ steps.platfom-svc-docker-metadata.outputs.labels }}
```

**Comment by tatality173** [comment]
jasondamour:empty-images

**Comment by tatality173** [comment]
// docker-bake.hcl
target "docker-metadata-action" {}

target "build" {
  inherits = ["docker-metadata-action"]
  context = "./"
  dockerfile = "Dockerfile"
  platforms = [
    "linux/amd64",
    "linux/arm/v6",
    "linux/arm/v7",
    "linux/arm64",
    "linux/386"
  ]
}

**Comment by jasondamour** [comment]
@tatality173 ??? What are you trying to say?

**Comment by jasondamour** [comment]
@crazy-max thoughts?

**Comment by irux** [comment]
any updates on this ?

**Review by crazy-max — CHANGES_REQUESTED** [review]
Very sorry for the delay!

Can you rebase?

**Comment by jasondamour** [comment]
Updated from master. @crazy-max I don't really understand the testing framework, can you give some pointers

**Comment by crazy-max** [comment]
> Updated from master.

Can you do a proper rebase instead of merge commit please?

> I don't really understand the testing framework, can you give some pointers

Would need extra tests https://github.com/docker/metadata-action/blob/master/__tests__/meta.test.ts to test the case when no image is set. One in this suite https://github.com/docker/metadata-action/blob/879dcbb708d40f8b8679d4f7941b938a086e23a7/__tests__/meta.test.ts#L125 would be fine.

**Comment by irux** [comment]
any news on this ? @crazy-max @jasondamour

**Pull request closed without merging**
